# Generated by Django 5.2.7 on 2025-10-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_question_answeroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='—', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='—', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='result_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_to_complete',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests_app.test'),
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
    ]
