# Generated by Django 5.2.7 on 2025-10-13 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_question_correct_option_question_option_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions_count',
        ),
        migrations.AddField(
            model_name='question',
            name='score_a',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='score_b',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='question',
            name='score_c',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_to_complete',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.test'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
