# Generated by Django 5.2.7 on 2025-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='theme',
            field=models.CharField(choices=[('relationships', 'Отношения 💞'), ('burnout', 'Выгорание 🔥'), ('boundaries', 'Границы 🧱'), ('self', 'Саморазвитие 🌿')], default='self', max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_to_complete',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
