"""
Django settings for mydjangoproject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# --- Безопасность / режим ---
SECRET_KEY = 'django-insecure-ufb1$reh#uqc6gut=23-2e7ccgbux5hzwwux$y0#7@7fj7!2(z'  # вынеси в переменные окружения перед продом
DEBUG = True

# при деплое добавь свой домен вместо yourdomain.kz
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.pythonanywhere.com', 'yourdomain.kz']

# --- Приложения ---
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ваши приложения
    'articles',
    'users',
    'tests_app',
]

# --- Middleware ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shanyraq_project.urls'

# --- Шаблоны ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # папка общих шаблонов
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shanyraq_project.wsgi.application'

# --- База данных (SQLite по умолчанию) ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- Валидаторы паролей ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Локализация ---
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Asia/Almaty'
USE_I18N = True
USE_TZ = True

# --- Статика и медиа ---
# В разработке ваши css/js кладите в папку ./static
# При деплое выполните: python manage.py collectstatic — файлы соберутся в STATIC_ROOT
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']      # где лежит статика в dev
STATIC_ROOT = BASE_DIR / 'staticfiles'        # куда собирать статику для prod

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'               # куда загружаются файлы (картинки и т.п.)

# --- Прочее ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

JAZZMIN_SETTINGS = {
    "site_title": "Shanyraq Admin",
    "site_header": "Shanyraq Dashboard",
    "welcome_sign": "Добро пожаловать, Ризат!",
    "copyright": "© 2025 Shanyraq Journal",
}
